version: '3.2'
services:
  consul:
    container_name: consul
    image: gliderlabs/consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    command: "-bootstrap"
    restart: always
    volumes:
      - ./consul/server.json:/config/server.json
    environment:
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8600_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul'
    networks:
      - consul

  registrator:
    container_name: consul_registrator
    image: gliderlabs/registrator
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: "-internal consul://consul:8500"
    restart: always
    depends_on: 
      - consul
    networks:
      - consul

  redis:
    container_name: consul_redis
    image: redis:4.0
    environment:
      SERVICE_6379_NAME: 'redis'
    restart: always
    volumes:
      - ./data/redis:/data
    depends_on:
      - consul
    networks:
      - consul  
  
  dnsmasq:
    container_name: consul_dnsmasq
    image: jpillora/dnsmasq
    restart: always
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf.template
      - ./dnsmasq/entrypoint.sh:/etc/entrypoint.sh
    entrypoint: [ "/etc/entrypoint.sh" ]
    ports:
      - "5380:8080"
      - "53:53/udp"
    depends_on:
      - consul
      - nginx
    networks:
      - consul  

  nginx:
    hostname: consul_nginx
    container_name: consul_nginx
    image: nginx:1.10.2
    environment:
      SERVICE_443_IGNORE: 'yes'
      SERVICE_80_NAME: 'consul_nginx'
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - consul
    
networks:
  consul:
    external: true