version: "3.2"
services:
  consul:
    container_name: consul
    image: gliderlabs/consul-server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    command: "-bootstrap"
    restart: always
    volumes:
      - ./consul/server.json:/config/server.json
    environment:
      SERVICE_8300_IGNORE: "yes"
      SERVICE_8301_IGNORE: "yes"
      SERVICE_8302_IGNORE: "yes"
      SERVICE_8400_IGNORE: "yes"
      SERVICE_8600_IGNORE: "yes"
      SERVICE_8500_NAME: "consul"
    networks:
      - consul

  registrator:
    container_name: consul_registrator
    image: gliderlabs/registrator
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: "-internal consul://consul:8500"
    restart: always
    depends_on:
      - consul
    networks:
      - consul

  redis:
    container_name: consul_redis
    image: redis:4.0
    environment:
      SERVICE_6379_NAME: "redis"
    restart: always
    volumes:
      - ./data/redis:/data:cached
    depends_on:
      - consul
    networks:
      - consul

  dnsmasq:
    container_name: consul_dnsmasq
    image: jpillora/dnsmasq
    restart: always
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf.template
      - ./dnsmasq/entrypoint.sh:/etc/entrypoint.sh
    entrypoint: ["/etc/entrypoint.sh"]
    ports:
      - "5380:8080"
    depends_on:
      - consul
      - nginx
    networks:
      - consul

  nginx:
    hostname: consul_nginx
    container_name: consul_nginx
    image: nginx:1.16.0
    environment:
      SERVICE_443_IGNORE: "yes"
      SERVICE_80_NAME: "consul-nginx"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/entrypoint.sh:/etc/entrypoint.sh
    entrypoint: ["/etc/entrypoint.sh"]
    networks:
      - consul

  mysql:
    container_name: consul_mysql
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql:rw,delegated
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      SERVICE_NAME: "consul-mysql"
      TZ: "America/Sao_Paulo"
      SERVICE_3306_NAME: "consul-mysql"
      SERVICE_33060_IGNORE: "yes"
    ports:
      - "33060:3306"
    networks:
      - consul

networks:
  consul:
    external: true